In [48]:
import numpy as np
import pandas as pd

trip_df = pd.read_csv('raw_data/Taxi_Trips_20230112.csv')

In [49]:
trip_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6495570 entries, 0 to 6495569
Data columns (total 23 columns):
 #   Column                      Dtype  
---  ------                      -----  
 0   Trip ID                     object 
 1   Taxi ID                     object 
 2   Trip Start Timestamp        object 
 3   Trip End Timestamp          object 
 4   Trip Seconds                float64
 5   Trip Miles                  float64
 6   Pickup Census Tract         float64
 7   Dropoff Census Tract        float64
 8   Pickup Community Area       float64
 9   Dropoff Community Area      float64
 10  Fare                        float64
 11  Tips                        float64
 12  Tolls                       float64
 13  Extras                      float64
 14  Trip Total                  float64
 15  Payment Type                object 
 16  Company                     object 
 17  Pickup Centroid Latitude    float64
 18  Pickup Centroid Longitude   float64
 19  Pickup Centroid Locat

In [50]:
trip_df.head

<bound method NDFrame.head of                                           Trip ID  \
0        0fca59218b11688279d795c03c4d16f851f13fa0   
1        1e539d6e7501164c6b76b761c3152c235e206d59   
2        2b3c5200439d51f626b60380809bbbcca766a85b   
3        45b2ea39cfff64d61a46ef016e16f8ee74e9ed23   
4        464df6aaaf97ca8745985c2a5b2e481067a2bfb6   
...                                           ...   
6495565  ee7cce18a4b24e080366930ab5ec72d1aeb6556c   
6495566  f3a139c0df3513324ff3f699bf40db2e84291e3a   
6495567  f74fa03a6cf8cdcf668d0726efa1671d398b4450   
6495568  fa9c5a9388fe0d704452ae7bf3ccb917aa39c125   
6495569  fd4f3f628496b076e06a91e6933bb12489e1c65a   

                                                   Taxi ID  \
0        e2c349c7cbb608d552aa0b5814031943f13641ef9e50d8...   
1        4ab7a7510c1ebcc9b2e3eaa7bdd6508dbea34da7986aca...   
2        8c76eb82f069c0731a0049cb78898f02cc5ac6990244c9...   
3        a688de71e9eb70603ba839dc7faf949968ae3e971e0575...   
4        8b1a88e5a09cfd

In [51]:
nan_rows_specific = trip_df[trip_df[['Pickup Centroid Longitude', 'Pickup Centroid Latitude', 'Dropoff Centroid Longitude', 'Dropoff Centroid Latitude']].isnull().any(axis=1)]
nan_rows_specific

Trip ID  \
8        5bd5f7e751eb7a5708edfb81980ab24c6bb2b7a8   
13       b6b2e5b4de1d775f1979d1b2e728cd7418dc329a   
15       c22902fdf0548a8d12ce49015763fcb9330d4080   
24       061aff7b0f8c46651d0f30e2f3e38acafb6ac81f   
44       4f65ab9c12a50ab0e5dcc8711524d4a789b0c83f   
...                                           ...   
6495510  327fa02e9cb1cc29e7898cf98830f6ade295f9e9   
6495528  5e3f05fac03791828973a9d5e273d756478e76a5   
6495554  cb50d6951086242beccb8fe7d248cfad3fab3dd7   
6495567  f74fa03a6cf8cdcf668d0726efa1671d398b4450   
6495568  fa9c5a9388fe0d704452ae7bf3ccb917aa39c125   

                                                   Taxi ID  \
8        7cb607b940a690e65b20dec20182d2646d3306f725130c...   
13       42e3ec7750e4be6e56c47bcdefe5cb86ddb0d0c65bcf4d...   
15       1bb875f74db6b3d8bcab27f6784218036ec738c201e533...   
24       222a0a55fe5180e292a8e128804e081fa50b05a0329775...   
44       cf278f6c67e799170264672cf78527e136318d96aefd5f...   
...                                                    ...   
6495510  15ddbeeb791d41c7683b885617281c0b548544f189ee36...   
6495528  ae61536025042a43c682f2450eaa073da8c7a7f736aec5...   
6495554  179f1a051e9e6d3fc0726628962faff68506086ee8df14...   
6495567  2fea69c8a6e08471bc4339a05e9ee7955bef68d791f77a...   
6495568  9a3b307a7d2c71565a27a2bcef5560f576240023bf21ca...   

           Trip Start Timestamp      Trip End Timestamp  Trip Seconds  \
8        01/01/2023 12:00:00 AM  01/01/2023 12:30:00 AM        2040.0   
13       01/01/2023 12:00:00 AM  01/01/2023 12:15:00 AM        1444.0   
15       01/01/2023 12:00:00 AM  01/01/2023 12:00:00 AM           6.0   
24       01/01/2023 12:00:00 AM  01/01/2023 12:15:00 AM         938.0   
44       01/01/2023 12:00:00 AM  01/01/2023 12:45:00 AM        1817.0   
...                         ...                     ...           ...   
6495510  12/31/2023 11:45:00 PM  01/01/2024 12:00:00 AM        1080.0   
6495528  12/31/2023 11:45:00 PM  01/01/2024 12:30:00 AM        1980.0   
6495554  12/31/2023 11:45:00 PM  01/01/2024 12:00:00 AM        1383.0   
6495567  12/31/2023 11:45:00 PM  01/01/2024 12:00:00 AM        1473.0   
6495568  12/31/2023 11:45:00 PM  12/31/2023 11:45:00 PM         358.0   

         Trip Miles  Pickup Census Tract  Dropoff Census Tract  \
8             17.30                  NaN                   NaN   
13            15.36                  NaN                   NaN   
15             0.07                  NaN                   NaN   
24             7.48                  NaN                   NaN   
44            17.84                  NaN          1.703132e+10   
...             ...                  ...                   ...   
6495510        8.10                  NaN                   NaN   
6495528        0.00                  NaN                   NaN   
6495554       17.95                  NaN                   NaN   
6495567        9.94                  NaN                   NaN   
6495568        2.05                  NaN                   NaN   

         Pickup Community Area  Dropoff Community Area  ...  Extras  \
8                         76.0                     NaN  ...    32.0   
13                        76.0                     NaN  ...    29.0   
15                         NaN                     NaN  ...     0.0   
24                        76.0                     NaN  ...     6.5   
44                         NaN                    32.0  ...     5.0   
...                        ...                     ...  ...     ...   
6495510                   56.0                     NaN  ...    16.5   
6495528                    8.0                     NaN  ...     7.0   
6495554                   28.0                     NaN  ...     0.0   
6495567                   56.0                     NaN  ...    18.0   
6495568                   76.0                     NaN  ...     4.0   

         Trip Total  Payment Type                       Company  \
8             86.50   Credit Card                    Globe Taxi   
13 

In [52]:
trip_df = trip_df.dropna(subset=['Pickup Centroid Longitude', 'Pickup Centroid Latitude', 'Dropoff Centroid Longitude', 'Dropoff Centroid Latitude'])

trip_df

Trip ID  \
0        0fca59218b11688279d795c03c4d16f851f13fa0   
1        1e539d6e7501164c6b76b761c3152c235e206d59   
2        2b3c5200439d51f626b60380809bbbcca766a85b   
3        45b2ea39cfff64d61a46ef016e16f8ee74e9ed23   
4        464df6aaaf97ca8745985c2a5b2e481067a2bfb6   
...                                           ...   
6495563  ec183abaa7ff142f17ebcdafa1f3d4e611a9f494   
6495564  ed445ada05f17c5f359892eda3c329e1445b5e7b   
6495565  ee7cce18a4b24e080366930ab5ec72d1aeb6556c   
6495566  f3a139c0df3513324ff3f699bf40db2e84291e3a   
6495569  fd4f3f628496b076e06a91e6933bb12489e1c65a   

                                                   Taxi ID  \
0        e2c349c7cbb608d552aa0b5814031943f13641ef9e50d8...   
1        4ab7a7510c1ebcc9b2e3eaa7bdd6508dbea34da7986aca...   
2        8c76eb82f069c0731a0049cb78898f02cc5ac6990244c9...   
3        a688de71e9eb70603ba839dc7faf949968ae3e971e0575...   
4        8b1a88e5a09cfd55ca72d267f00f56fa50a42aa322bdfe...   
...                                                    ...   
6495563  f6d1b6c930d62f6d8cbbd8f86a593ff057408c82f76474...   
6495564  4b034948aceedd53262ae713f864b0364953a1852b6b24...   
6495565  adb1cb74113851b651b474182fbe95a9663783779db8cc...   
6495566  9b48ad5744e86450fb4db78e7095a6827bafc43a6a9d9a...   
6495569  41ba5cfc7d59a833c94ed0b59fcc8a5f3aa5ca1b291325...   

           Trip Start Timestamp      Trip End Timestamp  Trip Seconds  \
0        01/01/2023 12:00:00 AM  01/01/2023 12:15:00 AM        1037.0   
1        01/01/2023 12:00:00 AM  01/01/2023 12:15:00 AM        1341.0   
2        01/01/2023 12:00:00 AM  01/01/2023 12:15:00 AM         844.0   
3        01/01/2023 12:00:00 AM  01/01/2023 12:00:00 AM         361.0   
4        01/01/2023 12:00:00 AM  01/01/2023 12:15:00 AM         704.0   
...                         ...                     ...           ...   
6495563  12/31/2023 11:45:00 PM  01/01/2024 12:00:00 AM         786.0   
6495564  12/31/2023 11:45:00 PM  12/31/2023 11:45:00 PM           4.0   
6495565  12/31/2023 11:45:00 PM  01/01/2024 12:00:00 AM        1310.0   
6495566  12/31/2023 11:45:00 PM  01/01/2024 12:00:00 AM        1228.0   
6495569  12/31/2023 11:45:00 PM  01/01/2024 12:00:00 AM         427.0   

         Trip Miles  Pickup Census Tract  Dropoff Census Tract  \
0              4.82                  NaN                   NaN   
1             16.63                  NaN                   NaN   
2              3.84                  NaN                   NaN   
3              0.63                  NaN                   NaN   
4              0.99                  NaN                   NaN   
...             ...                  ...                   ...   
6495563        2.02         1.703108e+10          1.703133e+10   
6495564        0.00         1.703132e+10          1.703132e+10   
6495565       18.23                  NaN                   NaN   
6495566        4.29                  NaN                   NaN   
6495569        1.28                  NaN                   NaN   

         Pickup Community Area  Dropoff Community Area  ...  Extras  \
0                          6.0                    32.0  ...     0.0   
1                         76.0                     8.0  ...     6.0   
2                         24.0                     8.0  ...     0.0   
3                         32.0                    32.0  ...     1.0   
4                         14.0                    14.0  ...     0.0   
...                        ...                     ...  ...     ...   
6495563                    8.0                    33.0  ...     0.0   
6495564                   32.0                    32.0  ...     0.0   
6495565                   28.0                    76.0  ...     0.0   
6495566                    6.0                    21.0  ...     0.0   
6495569                   24.0                     8.0  ...     0.0   

         Trip Total  Payment Type                       Company  \
0             19.50   Credit Card  Taxicab Insurance Agency Llc   
1  

In [53]:
import pandas as pd

# 假设这是加载数据的代码
# df = pd.read_csv('path_to_your_data.csv')

# 将时间戳列转换为datetime类型
trip_df['Trip Start Timestamp'] = pd.to_datetime(trip_df['Trip Start Timestamp'])
trip_df['Trip End Timestamp'] = pd.to_datetime(trip_df['Trip End Timestamp'])

# 找出时间范围
start_time_min = trip_df['Trip Start Timestamp'].min()
end_time_max = trip_df['Trip End Timestamp'].max()

print(f"时间范围从 {start_time_min} 到 {end_time_max}")

AnonymousUser\AppData\Local\Temp\ipykernel_27324\807657203.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trip_df['Trip Start Timestamp'] = pd.to_datetime(trip_df['Trip Start Timestamp'])


时间范围从 2023-01-01 00:00:00 到 2024-01-02 13:00:00


AnonymousUser\AppData\Local\Temp\ipykernel_27324\807657203.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trip_df['Trip End Timestamp'] = pd.to_datetime(trip_df['Trip End Timestamp'])


In [54]:
import pandas as pd

# 假设df是已加载的DataFrame
# 首先，转换日期时间列
trip_df['Trip Start Timestamp'] = pd.to_datetime(trip_df['Trip Start Timestamp'])
trip_df['Trip End Timestamp'] = pd.to_datetime(trip_df['Trip End Timestamp'])

# 然后，设置时间范围
start_date = '2023-06-01'
end_date = '2024-01-01'

# 筛选数据
trip_df = trip_df[(trip_df['Trip Start Timestamp'] >= start_date) & (trip_df['Trip Start Timestamp'] < end_date)]
trip_df = trip_df[(trip_df['Trip End Timestamp'] >= start_date) & (trip_df['Trip End Timestamp'] < end_date)]

# 查看结果
trip_df.info()


AnonymousUser\AppData\Local\Temp\ipykernel_27324\1799586310.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trip_df['Trip Start Timestamp'] = pd.to_datetime(trip_df['Trip Start Timestamp'])
AnonymousUser\AppData\Local\Temp\ipykernel_27324\1799586310.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trip_df['Trip End Timestamp'] = pd.to_datetime(trip_df['Trip End Timestamp'])


<class 'pandas.core.frame.DataFrame'>
Int64Index: 3513535 entries, 2609422 to 6495564
Data columns (total 23 columns):
 #   Column                      Dtype         
---  ------                      -----         
 0   Trip ID                     object        
 1   Taxi ID                     object        
 2   Trip Start Timestamp        datetime64[ns]
 3   Trip End Timestamp          datetime64[ns]
 4   Trip Seconds                float64       
 5   Trip Miles                  float64       
 6   Pickup Census Tract         float64       
 7   Dropoff Census Tract        float64       
 8   Pickup Community Area       float64       
 9   Dropoff Community Area      float64       
 10  Fare                        float64       
 11  Tips                        float64       
 12  Tolls                       float64       
 13  Extras                      float64       
 14  Trip Total                  float64       
 15  Payment Type                object        
 16  Company     

In [55]:
trip_df.head

<bound method NDFrame.head of                                           Trip ID  \
2609422  01b99a00c590a4df1af2f5a86c87a31450907bdd   
2609424  111052ef490e1b1b59311636ead9f384d19b970a   
2609425  14d661536fb9cbf261dcdf51e7df7f0d56a12b39   
2609426  16d98c0c6cd54966cc4f4dec806491857b670228   
2609427  16ee8eea0d749454c22e33b7b67e8d7d8c42c6c4   
...                                           ...   
6495552  c5ad9b572bff9d5cb9a8cf0da173789f7910a835   
6495553  c6cb3aad561e0c407239333d535a4922540f9adc   
6495557  dcfbaa5d01e81e18637185fc5e822d6a08456f59   
6495559  e2b8bea5dbc60464ff88ba8dc8b66836513101e8   
6495564  ed445ada05f17c5f359892eda3c329e1445b5e7b   

                                                   Taxi ID  \
2609422  a33e818f102d2dc8ba6ec21c582cf1aa1cd034a85db091...   
2609424  eead1e2c21b26570411277cb384d3d8d072fc6da913b06...   
2609425  180309cc29892cd16348ef74d7dd6f33af87e585a29b62...   
2609426  ffa4a7ea614ef7d2eac427f6f1a0af6a5298a57224da0b...   
2609427  0bea3de3c36237

In [56]:
import pandas as pd

# 假设这是加载数据的代码
# df = pd.read_csv('path_to_your_data.csv')

# 将时间戳列转换为datetime类型
trip_df['Trip Start Timestamp'] = pd.to_datetime(trip_df['Trip Start Timestamp'])
trip_df['Trip End Timestamp'] = pd.to_datetime(trip_df['Trip End Timestamp'])

# 找出时间范围
start_time_min = trip_df['Trip Start Timestamp'].min()
end_time_max = trip_df['Trip End Timestamp'].max()

print(f"时间范围从 {start_time_min} 到 {end_time_max}")

时间范围从 2023-06-01 00:00:00 到 2023-12-31 23:45:00


In [57]:
min_pickup_longitude = trip_df['Pickup Centroid Longitude'].min()
max_pickup_longitude = trip_df['Pickup Centroid Longitude'].max()
min_pickup_latitude = trip_df['Pickup Centroid Latitude'].min()
max_pickup_latitude = trip_df['Pickup Centroid Latitude'].max()
min_dropoff_longitude = trip_df['Dropoff Centroid Longitude'].min()
max_dropoff_longitude = trip_df['Dropoff Centroid Longitude'].max()
min_dropoff_latitude = trip_df['Dropoff Centroid Latitude'].min()
max_dropoff_latitude = trip_df['Dropoff Centroid Latitude'].max()

# 打印结果
print("Pickup Longitude - Min:", min_pickup_longitude, "Max:", max_pickup_longitude)
print("Pickup Latitude - Min:", min_pickup_latitude, "Max:", max_pickup_latitude)
print("Dropoff Longitude - Min:", min_dropoff_longitude, "Max:", max_dropoff_longitude)
print("Dropoff Latitude - Min:", min_dropoff_latitude, "Max:", max_dropoff_latitude)

Pickup Longitude - Min: -87.913624596 Max: -87.534902901
Pickup Latitude - Min: 41.650221676 Max: 42.021223593
Dropoff Longitude - Min: -87.913624596 Max: -87.534902901
Dropoff Latitude - Min: 41.660136051 Max: 42.021223593


In [58]:
# 找到所有经度和纬度的最大和最小值
min_longitude = min(trip_df['Pickup Centroid Longitude'].min(), trip_df['Dropoff Centroid Longitude'].min())
max_longitude = max(trip_df['Pickup Centroid Longitude'].max(), trip_df['Dropoff Centroid Longitude'].max())
min_latitude = min(trip_df['Pickup Centroid Latitude'].min(), trip_df['Dropoff Centroid Latitude'].min())
max_latitude = max(trip_df['Pickup Centroid Latitude'].max(), trip_df['Dropoff Centroid Latitude'].max())

# 打印结果
print("Global Minimum Longitude:", min_longitude)
print("Global Maximum Longitude:", max_longitude)
print("Global Minimum Latitude:", min_latitude)
print("Global Maximum Latitude:", max_latitude)

Global Minimum Longitude: -87.913624596
Global Maximum Longitude: -87.534902901
Global Minimum Latitude: 41.650221676
Global Maximum Latitude: 42.021223593


In [59]:
import pandas as pd
import numpy as np
import folium
from folium.plugins import HeatMap

# 创建地图对象，以芝加哥市中心为中心
map = folium.Map(location=[41.8781, -87.6298], zoom_start=12)  # 调整地图的初始位置和缩放级别

# 添加热力图层
sampled_data = trip_df.sample(n=300000, random_state=42)
heatmap_data = sampled_data[['Pickup Centroid Latitude', 'Pickup Centroid Longitude']].values.tolist()  # 将数据转换为列表
HeatMap(heatmap_data).add_to(map)

# heatmap_data = [[row['Pickup Centroid Latitude'], row['Pickup Centroid Longitude']] for index, row in trip_df.iterrows()]
# HeatMap(heatmap_data).add_to(map)

# sampled_data
# 保存地图
map.save('Chicago_Taxi_Pickup_Heatmap.html')

print("Heatmap has been created and saved as 'Chicago_Taxi_Pickup_Heatmap.html'")

Heatmap has been created and saved as 'Chicago_Taxi_Pickup_Heatmap.html'


In [60]:
trip_df.to_csv('clean_trip.csv', index=False)

## Clean Trip

In [61]:
clean_trip = pd.read_csv('clean_trip.csv')

In [62]:
# 定义网格尺寸
n_rows = 30
n_columns = 20
lon_width = (87.913624596 - 87.534902901) / n_columns
lat_height = (42.021223593 - 41.650221676) / n_rows

# 计算网格编号
def calculate_grid_id(lon, lat):
    lon_idx = int((lon + 87.913624596) / lon_width)
    lat_idx = int((42.021223593 - lat) / lat_height)
    return lon_idx + lat_idx * n_columns

# 为每个行程添加网格编号
clean_trip['pickup_grid_id'] = clean_trip.apply(lambda x: calculate_grid_id(x['Pickup Centroid Longitude'], x['Pickup Centroid Latitude']), axis=1)
clean_trip['dropoff_grid_id'] = clean_trip.apply(lambda x: calculate_grid_id(x['Dropoff Centroid Longitude'], x['Dropoff Centroid Latitude']), axis=1)

# 打印更新后的DataFrame信息
print(clean_trip[['pickup_grid_id', 'dropoff_grid_id']].head())

   pickup_grid_id  dropoff_grid_id
0              60              275
1              60              194
2             367              293
3             235              133
4             233              194


In [63]:
# 按pickup_grid_id分组并计算每组的数据数
grouped_pickup_counts = clean_trip.groupby('pickup_grid_id').size()

# 将结果转换为DataFrame并重置索引，方便查看
grouped_pickup_counts_df = grouped_pickup_counts.reset_index(name='count')

# 打印结果
print(grouped_pickup_counts_df)

     pickup_grid_id  count
0                11     15
1                12  17849
2                13     31
3                20      7
4                25    790
..              ...    ...
200             574   7292
201             576      7
202             579   1413
203             596   2893
204             616      1

[205 rows x 2 columns]


In [72]:
clean_trip

Trip ID  \
0        01b99a00c590a4df1af2f5a86c87a31450907bdd   
1        111052ef490e1b1b59311636ead9f384d19b970a   
2        14d661536fb9cbf261dcdf51e7df7f0d56a12b39   
3        16d98c0c6cd54966cc4f4dec806491857b670228   
4        16ee8eea0d749454c22e33b7b67e8d7d8c42c6c4   
...                                           ...   
3513530  c5ad9b572bff9d5cb9a8cf0da173789f7910a835   
3513531  c6cb3aad561e0c407239333d535a4922540f9adc   
3513532  dcfbaa5d01e81e18637185fc5e822d6a08456f59   
3513533  e2b8bea5dbc60464ff88ba8dc8b66836513101e8   
3513534  ed445ada05f17c5f359892eda3c329e1445b5e7b   

                                                   Taxi ID  \
0        a33e818f102d2dc8ba6ec21c582cf1aa1cd034a85db091...   
1        eead1e2c21b26570411277cb384d3d8d072fc6da913b06...   
2        180309cc29892cd16348ef74d7dd6f33af87e585a29b62...   
3        ffa4a7ea614ef7d2eac427f6f1a0af6a5298a57224da0b...   
4        0bea3de3c36237d68b009b24ee3db86c78e9e618a73a3b...   
...                                                    ...   
3513530  c7a8a53874bbcdb11e70a488485e8bdd0bb8cc0de8f5d9...   
3513531  bca79085da78d157007711d04c6e06f655ee5eafb1e5b6...   
3513532  2659a61c08f91c6efd9e7d7947a00006a7bc26aa518241...   
3513533  884655d853cbe41e1cdf747969f0dc5b55ed2d5f76c09a...   
3513534  4b034948aceedd53262ae713f864b0364953a1852b6b24...   

        Trip Start Timestamp   Trip End Timestamp  Trip Seconds  Trip Miles  \
0        2023-06-01 00:00:00  2023-06-01 00:30:00        2031.0       21.03   
1        2023-06-01 00:00:00  2023-06-01 00:30:00        1412.0       17.83   
2        2023-06-01 00:00:00  2023-06-01 00:45:00        2517.0        7.50   
3        2023-06-01 00:00:00  2023-06-01 00:15:00         952.0        6.41   
4        2023-06-01 00:00:00  2023-06-01 00:15:00         480.0        1.50   
...                      ...                  ...           ...         ...   
3513530  2023-12-31 23:45:00  2023-12-31 23:45:00           7.0        0.00   
3513531  2023-12-31 23:45:00  2023-12-31 23:45:00         839.0        7.17   
3513532  2023-12-31 23:45:00  2023-12-31 23:45:00         300.0        1.80   
3513533  2023-12-31 23:45:00  2023-12-31 23:45:00         279.0        1.51   
3513534  2023-12-31 23:45:00  2023-12-31 23:45:00           4.0        0.00   

         Pickup Census Tract  Dropoff Census Tract  Pickup Community Area  \
0                        NaN                   NaN                   76.0   
1                        NaN                   NaN                   76.0   
2                        NaN                   NaN                   56.0   
3                        NaN                   NaN                   32.0   
4                        NaN                   NaN                   28.0   
...                      ...                   ...                    ...   
3513530                  NaN                   NaN                   28.0   
3513531                  NaN                   NaN                   76.0   
3513532                  NaN                   NaN                   76.0   
3513533                  NaN                   NaN                   49.0   
3513534         1.703132e+10          1.703132e+10                   32.0   

         Dropoff Community Area  ...  Payment Type  \
0                          33.0  ...   Credit Card   
1                           8.0  ...   Credit Card   
2                          60.0  ...          Cash   
3                           6.0  ...   Credit Card   
4                           8.0  ...   Credit Card   
...                         ...  ...           ...   
3513530                    28.0  ...   Credit Card   
3513531                    10.0  ...   Credit Card   
3513532                     7.0  ...   Credit Card   
3513533                    49.0  ...          Cash   
3513534                    32.0  ...   Credit Card   

                                Company  Pickup Centroid Latitude  \
0                              Sun Taxi                 41.980264   

In [73]:
# 读取映射表CSV文件并将其转换回字典格式

# 读取CSV文件到DataFrame
mapping_df_loaded = pd.read_csv('grid_id_mapping.csv')

# 将DataFrame转换为字典
grid_id_mapping = dict(zip(mapping_df_loaded['Old_Grid_ID'], mapping_df_loaded['New_Grid_ID']))

grid_id_mapping

{11: 0,
 12: 1,
 13: 2,
 25: 3,
 26: 4,
 30: 5,
 31: 6,
 32: 7,
 33: 8,
 46: 9,
 50: 10,
 51: 11,
 52: 12,
 53: 13,
 60: 14,
 65: 15,
 66: 16,
 67: 17,
 68: 18,
 69: 19,
 70: 20,
 71: 21,
 72: 22,
 73: 23,
 87: 24,
 88: 25,
 89: 26,
 90: 27,
 91: 28,
 92: 29,
 93: 30,
 94: 31,
 105: 32,
 106: 33,
 107: 34,
 108: 35,
 109: 36,
 110: 37,
 111: 38,
 112: 39,
 113: 40,
 114: 41,
 125: 42,
 126: 43,
 127: 44,
 128: 45,
 129: 46,
 130: 47,
 131: 48,
 132: 49,
 133: 50,
 134: 51,
 146: 52,
 147: 53,
 148: 54,
 149: 55,
 150: 56,
 151: 57,
 152: 58,
 153: 59,
 154: 60,
 166: 61,
 167: 62,
 168: 63,
 169: 64,
 170: 65,
 171: 66,
 172: 67,
 173: 68,
 174: 69,
 187: 70,
 188: 71,
 189: 72,
 190: 73,
 191: 74,
 192: 75,
 193: 76,
 194: 77,
 195: 78,
 207: 79,
 208: 80,
 209: 81,
 210: 82,
 211: 83,
 212: 84,
 213: 85,
 214: 86,
 215: 87,
 227: 88,
 228: 89,
 229: 90,
 230: 91,
 231: 92,
 232: 93,
 233: 94,
 234: 95,
 235: 96,
 247: 97,
 248: 98,
 249: 99,
 250: 100,
 251: 101,
 252: 102,
 253: 103

In [90]:
# 为数据集应用新的网格编号
clean_trip['new_pickup_grid_id'] = clean_trip['pickup_grid_id'].map(grid_id_mapping)
clean_trip['new_dropoff_grid_id'] = clean_trip['dropoff_grid_id'].map(grid_id_mapping)

# 删除那些新网格编号为NaN的行
filtered_trip_df = clean_trip.dropna(subset=['new_pickup_grid_id', 'new_dropoff_grid_id'])

In [91]:
# 按pickup_grid_id分组并计算每组的数据数
grouped_pickup_counts = filtered_trip_df.groupby('new_pickup_grid_id').size()

# 将结果转换为DataFrame并重置索引，方便查看
grouped_pickup_counts_df = grouped_pickup_counts.reset_index(name='count')

# 打印结果
print(grouped_pickup_counts_df)

     new_pickup_grid_id  count
0                     0     15
1                     1  17606
2                     2     31
3                     3    766
4                     6  22617
..                  ...    ...
171                 209   8624
172                 213   4618
173                 214      4
174                 216      3
175                 217      3

[176 rows x 2 columns]


In [92]:
filtered_trip_df

Trip ID  \
0        01b99a00c590a4df1af2f5a86c87a31450907bdd   
1        111052ef490e1b1b59311636ead9f384d19b970a   
2        14d661536fb9cbf261dcdf51e7df7f0d56a12b39   
3        16d98c0c6cd54966cc4f4dec806491857b670228   
4        16ee8eea0d749454c22e33b7b67e8d7d8c42c6c4   
...                                           ...   
3513529  ae20c529b8423608f3f0bfcfa243100219f1241e   
3513530  c5ad9b572bff9d5cb9a8cf0da173789f7910a835   
3513532  dcfbaa5d01e81e18637185fc5e822d6a08456f59   
3513533  e2b8bea5dbc60464ff88ba8dc8b66836513101e8   
3513534  ed445ada05f17c5f359892eda3c329e1445b5e7b   

                                                   Taxi ID  \
0        a33e818f102d2dc8ba6ec21c582cf1aa1cd034a85db091...   
1        eead1e2c21b26570411277cb384d3d8d072fc6da913b06...   
2        180309cc29892cd16348ef74d7dd6f33af87e585a29b62...   
3        ffa4a7ea614ef7d2eac427f6f1a0af6a5298a57224da0b...   
4        0bea3de3c36237d68b009b24ee3db86c78e9e618a73a3b...   
...                                                    ...   
3513529  d3e38cf4471f5b65aa0c41a155252c395b7c8593ac6fb5...   
3513530  c7a8a53874bbcdb11e70a488485e8bdd0bb8cc0de8f5d9...   
3513532  2659a61c08f91c6efd9e7d7947a00006a7bc26aa518241...   
3513533  884655d853cbe41e1cdf747969f0dc5b55ed2d5f76c09a...   
3513534  4b034948aceedd53262ae713f864b0364953a1852b6b24...   

        Trip Start Timestamp   Trip End Timestamp  Trip Seconds  Trip Miles  \
0        2023-06-01 00:00:00  2023-06-01 00:30:00        2031.0       21.03   
1        2023-06-01 00:00:00  2023-06-01 00:30:00        1412.0       17.83   
2        2023-06-01 00:00:00  2023-06-01 00:45:00        2517.0        7.50   
3        2023-06-01 00:00:00  2023-06-01 00:15:00         952.0        6.41   
4        2023-06-01 00:00:00  2023-06-01 00:15:00         480.0        1.50   
...                      ...                  ...           ...         ...   
3513529  2023-12-31 23:45:00  2023-12-31 23:45:00           1.0        0.04   
3513530  2023-12-31 23:45:00  2023-12-31 23:45:00           7.0        0.00   
3513532  2023-12-31 23:45:00  2023-12-31 23:45:00         300.0        1.80   
3513533  2023-12-31 23:45:00  2023-12-31 23:45:00         279.0        1.51   
3513534  2023-12-31 23:45:00  2023-12-31 23:45:00           4.0        0.00   

         Pickup Census Tract  Dropoff Census Tract  Pickup Community Area  \
0                        NaN                   NaN                   76.0   
1                        NaN                   NaN                   76.0   
2                        NaN                   NaN                   56.0   
3                        NaN                   NaN                   32.0   
4                        NaN                   NaN                   28.0   
...                      ...                   ...                    ...   
3513529                  NaN                   NaN                   27.0   
3513530                  NaN                   NaN                   28.0   
3513532                  NaN                   NaN                   76.0   
3513533                  NaN                   NaN                   49.0   
3513534         1.703132e+10          1.703132e+10                   32.0   

         Dropoff Community Area  ...  Pickup Centroid Latitude  \
0                          33.0  ...                 41.980264   
1                           8.0  ...                 41.980264   
2                          60.0  ...                 41.792592   
3                           6.0  ...                 41.878866   
4                           8.0  ...                 41.874005   
...                         ...  ...                       ...   
3513529                    27.0  ...                 41.878914   
3513530                    28.0  ...                 41.874005   
3513532                     7.0  ...                 41.980264   
3513533                    49.0  ...                 41.706588   
3513534                    32.0  ...                 41.8849

In [93]:
filtered_trip_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3291357 entries, 0 to 3513534
Data columns (total 27 columns):
 #   Column                      Dtype  
---  ------                      -----  
 0   Trip ID                     object 
 1   Taxi ID                     object 
 2   Trip Start Timestamp        object 
 3   Trip End Timestamp          object 
 4   Trip Seconds                float64
 5   Trip Miles                  float64
 6   Pickup Census Tract         float64
 7   Dropoff Census Tract        float64
 8   Pickup Community Area       float64
 9   Dropoff Community Area      float64
 10  Fare                        float64
 11  Tips                        float64
 12  Tolls                       float64
 13  Extras                      float64
 14  Trip Total                  float64
 15  Payment Type                object 
 16  Company                     object 
 17  Pickup Centroid Latitude    float64
 18  Pickup Centroid Longitude   float64
 19  Pickup Centroid Locat

In [94]:
# 删除指定列
columns_to_drop = ['Pickup Centroid Latitude', 'Pickup Centroid Longitude', 'Pickup Centroid Location', 
                   'Dropoff Centroid Latitude', 'Dropoff Centroid Longitude', 'Dropoff Centroid  Location', 
                   'pickup_grid_id', 'dropoff_grid_id']
filtered_trip_df.drop(columns=columns_to_drop, inplace=True)

# 输出到CSV文件
filtered_trip_df.to_csv('filtered_trip_df.csv', index=False)

## Filtered TRIP DF

In [95]:
import pandas as pd

filtered_trip_df = pd.read_csv('filtered_trip_df.csv')

In [96]:
filtered_trip_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3291357 entries, 0 to 3291356
Data columns (total 19 columns):
 #   Column                  Dtype  
---  ------                  -----  
 0   Trip ID                 object 
 1   Taxi ID                 object 
 2   Trip Start Timestamp    object 
 3   Trip End Timestamp      object 
 4   Trip Seconds            float64
 5   Trip Miles              float64
 6   Pickup Census Tract     float64
 7   Dropoff Census Tract    float64
 8   Pickup Community Area   float64
 9   Dropoff Community Area  float64
 10  Fare                    float64
 11  Tips                    float64
 12  Tolls                   float64
 13  Extras                  float64
 14  Trip Total              float64
 15  Payment Type            object 
 16  Company                 object 
 17  new_pickup_grid_id      int64  
 18  new_dropoff_grid_id     int64  
dtypes: float64(11), int64(2), object(6)
memory usage: 477.1+ MB


In [97]:
# 从 filtered_manhattan_df 中选择指定的列，创建 pickup_df
pickup_df = filtered_trip_df.loc[:, ['Trip Start Timestamp', 'new_pickup_grid_id']]

# 从 filtered_manhattan_df 中选择指定的列，创建 dropoff_df
dropoff_df = filtered_trip_df.loc[:, ['Trip End Timestamp', 'new_dropoff_grid_id']]

In [98]:
pickup_df.to_csv('pickup_df.csv', index=False)
dropoff_df.to_csv('dropoff_df.csv', index=False)

## Pickup DF

In [99]:
import pandas as pd

# 设置开始和结束日期
start_date = '2023-06-01 00:00:00'
end_date = '2023-12-31 23:59:59'

# 生成时间序列，间隔为30分钟
time_slices = pd.date_range(start=start_date, end=end_date, freq='30T')

time_slices

DatetimeIndex(['2023-06-01 00:00:00', '2023-06-01 00:30:00',
               '2023-06-01 01:00:00', '2023-06-01 01:30:00',
               '2023-06-01 02:00:00', '2023-06-01 02:30:00',
               '2023-06-01 03:00:00', '2023-06-01 03:30:00',
               '2023-06-01 04:00:00', '2023-06-01 04:30:00',
               ...
               '2023-12-31 19:00:00', '2023-12-31 19:30:00',
               '2023-12-31 20:00:00', '2023-12-31 20:30:00',
               '2023-12-31 21:00:00', '2023-12-31 21:30:00',
               '2023-12-31 22:00:00', '2023-12-31 22:30:00',
               '2023-12-31 23:00:00', '2023-12-31 23:30:00'],
              dtype='datetime64[ns]', length=10272, freq='30T')

In [100]:
pickup_df = pd.read_csv('pickup_df.csv')
pickup_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3291357 entries, 0 to 3291356
Data columns (total 2 columns):
 #   Column                Dtype 
---  ------                ----- 
 0   Trip Start Timestamp  object
 1   new_pickup_grid_id    int64 
dtypes: int64(1), object(1)
memory usage: 50.2+ MB


In [101]:
# 将Trip Start Timestamp列转换为Datetime类型
pickup_df['Trip Start Timestamp'] = pd.to_datetime(pickup_df['Trip Start Timestamp'])

In [102]:
# 创建一个新列表示时间片段（每30分钟）
pickup_df['time_slice'] = pickup_df['Trip Start Timestamp'].dt.floor('30min')

# 按照时间片段和网格编号进行分组，并统计每个分组中的记录数
grouped = pickup_df.groupby(['time_slice', 'new_pickup_grid_id']).agg({'new_pickup_grid_id': 'count'})

In [103]:
grouped.head(10)

new_pickup_grid_id
time_slice new_pickup_grid_id                    
2023-06-01 13                                   1
           14                                  53
           17                                   1
           30                                   1
           50                                   2
           59                                   2
           75                                   2
           77                                  22
           80                                   1
           87                                   3

In [104]:
grouped.tail(10)

new_pickup_grid_id
time_slice          new_pickup_grid_id                    
2023-12-31 23:30:00 85                                   1
                    86                                   2
                    87                                   3
                    91                                   1
                    94                                   9
                    95                                   3
                    96                                  10
                    112                                  3
                    144                                  1
                    209                                  1

In [111]:
import numpy as np

# 将结果重塑为所需的形状
# time_slices = sorted(pickup_df['time_slice'].unique())  # 获取所有时间片段
grid_ids = list(range(220))  # 获取所有网格编号
pick_up = np.zeros((len(time_slices), len(grid_ids)), dtype=int)  # 创建空的结果数组

# 填充结果数组
for i, time_slice in enumerate(time_slices):
    for j, grid_id in enumerate(grid_ids):
        try:
            count = grouped.loc[(time_slice, grid_id), 'new_pickup_grid_id']
        except KeyError:
            count = 0
        pick_up[i, j] = count

# 输出结果
print(pick_up)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [112]:
pick_up.shape

(10272, 220)

In [123]:
np.save('pickup.npy', pick_up.T)

## Dropoff DF

In [114]:
import pandas as pd

# 设置开始和结束日期
start_date = '2023-06-01 00:00:00'
end_date = '2023-12-31 23:59:59'

# 生成时间序列，间隔为30分钟
time_slices = pd.date_range(start=start_date, end=end_date, freq='30T')

time_slices

DatetimeIndex(['2023-06-01 00:00:00', '2023-06-01 00:30:00',
               '2023-06-01 01:00:00', '2023-06-01 01:30:00',
               '2023-06-01 02:00:00', '2023-06-01 02:30:00',
               '2023-06-01 03:00:00', '2023-06-01 03:30:00',
               '2023-06-01 04:00:00', '2023-06-01 04:30:00',
               ...
               '2023-12-31 19:00:00', '2023-12-31 19:30:00',
               '2023-12-31 20:00:00', '2023-12-31 20:30:00',
               '2023-12-31 21:00:00', '2023-12-31 21:30:00',
               '2023-12-31 22:00:00', '2023-12-31 22:30:00',
               '2023-12-31 23:00:00', '2023-12-31 23:30:00'],
              dtype='datetime64[ns]', length=10272, freq='30T')

In [115]:
dropoff_df = pd.read_csv('dropoff_df.csv')
dropoff_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3291357 entries, 0 to 3291356
Data columns (total 2 columns):
 #   Column               Dtype 
---  ------               ----- 
 0   Trip End Timestamp   object
 1   new_dropoff_grid_id  int64 
dtypes: int64(1), object(1)
memory usage: 50.2+ MB


In [117]:
# 将Trip Start Timestamp列转换为Datetime类型
dropoff_df['Trip End Timestamp'] = pd.to_datetime(dropoff_df['Trip End Timestamp'])

In [118]:
# 创建一个新列表示时间片段（每30分钟）
dropoff_df['time_slice'] = dropoff_df['Trip End Timestamp'].dt.floor('30min')

# 按照时间片段和网格编号进行分组，并统计每个分组中的记录数
grouped = dropoff_df.groupby(['time_slice', 'new_dropoff_grid_id']).agg({'new_dropoff_grid_id': 'count'})

In [119]:
grouped.head(10)

new_dropoff_grid_id
time_slice new_dropoff_grid_id                     
2023-06-01 14                                     1
           27                                     1
           39                                     1
           47                                     2
           50                                     5
           57                                     1
           59                                     4
           75                                     4
           77                                    16
           80                                     1

In [120]:
grouped.tail(10)

new_dropoff_grid_id
time_slice          new_dropoff_grid_id                     
2023-12-31 23:30:00 94                                     9
                    95                                     3
                    96                                    13
                    112                                    4
                    114                                    1
                    139                                    1
                    153                                    2
                    174                                    2
                    190                                    1
                    209                                    1

In [121]:
import numpy as np

# 将结果重塑为所需的形状
# time_slices = sorted(pickup_df['time_slice'].unique())  # 获取所有时间片段
grid_ids = list(range(220))  # 获取所有网格编号
drop_off = np.zeros((len(time_slices), len(grid_ids)), dtype=int)  # 创建空的结果数组

# 填充结果数组
for i, time_slice in enumerate(time_slices):
    for j, grid_id in enumerate(grid_ids):
        try:
            count = grouped.loc[(time_slice, grid_id), 'new_dropoff_grid_id']
        except KeyError:
            count = 0
        drop_off[i, j] = count

# 输出结果
print(drop_off)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


In [122]:
drop_off.shape

(10272, 220)

In [124]:
np.save('dropoff.npy', drop_off.T)