## Combine & Filter

In [ ]:
import pandas as pd

# 读取数据
df1 = pd.read_csv('raw/yellow_tripdata_2016-01.csv')
df2 = pd.read_csv('raw/yellow_tripdata_2016-02.csv')
df3 = pd.read_csv('raw/yellow_tripdata_2016-03.csv')

In [ ]:
df1.info()

In [ ]:
# 选择需要的列
selected_columns = [
    'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count',
    'pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude'
]
df1_ = df1[selected_columns]
df2_ = df2[selected_columns]
df3_ = df3[selected_columns]

In [ ]:
# 合并数据
combined_df = pd.concat([df1_, df2_, df3_])

In [ ]:
combined_df.info()

In [ ]:
combined_df.tail()

In [ ]:
combined_df.shape

In [ ]:
pickup_min = combined_df['tpep_pickup_datetime'].min()
pickup_max = combined_df['tpep_pickup_datetime'].max()

print(pickup_min)
print(pickup_max)

In [ ]:
dropoff_min = combined_df['tpep_dropoff_datetime'].min()
dropoff_max = combined_df['tpep_dropoff_datetime'].max()

print(dropoff_min)
print(dropoff_max)

In [ ]:
# 定义日期范围
start_date = '2016-01-01 00:00:00'
end_date = '2016-03-31 23:59:59'

# 过滤数据，仅保留在指定日期范围内
filtered_df = combined_df[(combined_df['tpep_dropoff_datetime'] >= start_date) & 
                          (combined_df['tpep_dropoff_datetime'] <= end_date)]

In [ ]:
dropoff_min = filtered_df['tpep_dropoff_datetime'].min()
dropoff_max = filtered_df['tpep_dropoff_datetime'].max()

print(dropoff_min)
print(dropoff_max)

In [ ]:
filtered_df.shape

In [ ]:
# 过滤掉所有经纬度为0的行

filtered_df = filtered_df[
    (filtered_df['pickup_longitude'] != 0) & 
    (filtered_df['pickup_latitude'] != 0) & 
    (filtered_df['dropoff_longitude'] != 0) & 
    (filtered_df['dropoff_latitude'] != 0)
]

In [ ]:
filtered_df.shape

In [ ]:
filtered_df.info()

In [ ]:
# 检查是否有空值
null_presence = filtered_df.isnull().any()
print(null_presence)

In [ ]:
# 保存合并后的数据到新CSV
filtered_df.to_csv('filtered_df.csv', index=False)

## Filtered DF

In [1]:
import pandas as pd

filtered_df = pd.read_csv('filtered_df.csv')

In [2]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33916984 entries, 0 to 33916983
Data columns (total 7 columns):
 #   Column                 Dtype  
---  ------                 -----  
 0   tpep_pickup_datetime   object 
 1   tpep_dropoff_datetime  object 
 2   passenger_count        int64  
 3   pickup_longitude       float64
 4   pickup_latitude        float64
 5   dropoff_longitude      float64
 6   dropoff_latitude       float64
dtypes: float64(4), int64(1), object(2)
memory usage: 1.8+ GB


In [3]:
min_pickup_longitude = filtered_df['pickup_longitude'].min()
max_pickup_longitude = filtered_df['pickup_longitude'].max()
min_pickup_latitude = filtered_df['pickup_latitude'].min()
max_pickup_latitude = filtered_df['pickup_latitude'].max()
min_dropoff_longitude = filtered_df['dropoff_longitude'].min()
max_dropoff_longitude = filtered_df['dropoff_longitude'].max()
min_dropoff_latitude = filtered_df['dropoff_latitude'].min()
max_dropoff_latitude = filtered_df['dropoff_latitude'].max()

# 打印结果
print("Pickup Longitude - Min:", min_pickup_longitude, "Max:", max_pickup_longitude)
print("Pickup Latitude - Min:", min_pickup_latitude, "Max:", max_pickup_latitude)
print("Dropoff Longitude - Min:", min_dropoff_longitude, "Max:", max_dropoff_longitude)
print("Dropoff Latitude - Min:", min_dropoff_latitude, "Max:", max_dropoff_latitude)

Pickup Longitude - Min: -161.69866943359375 Max: 94.64386749267578
Pickup Latitude - Min: -77.03948974609375 Max: 66.85681915283203
Dropoff Longitude - Min: -161.69866943359375 Max: 38.89659118652344
Dropoff Latitude - Min: -77.03948974609375 Max: 405.3166809082031


In [4]:
# 找到所有经度和纬度的最大和最小值
min_longitude = min(filtered_df['pickup_longitude'].min(), filtered_df['dropoff_longitude'].min())
max_longitude = max(filtered_df['pickup_longitude'].max(), filtered_df['dropoff_longitude'].max())
min_latitude = min(filtered_df['pickup_latitude'].min(), filtered_df['dropoff_latitude'].min())
max_latitude = max(filtered_df['pickup_latitude'].max(), filtered_df['dropoff_latitude'].max())

# 打印结果
print("Global Minimum Longitude:", min_longitude)
print("Global Maximum Longitude:", max_longitude)
print("Global Minimum Latitude:", min_latitude)
print("Global Maximum Latitude:", max_latitude)

Global Minimum Longitude: -161.69866943359375
Global Maximum Longitude: 94.64386749267578
Global Minimum Latitude: -77.03948974609375
Global Maximum Latitude: 405.3166809082031


In [5]:
# 过滤纽约市正常范围的数据
nyc_filtered_df = filtered_df[
    (filtered_df['pickup_longitude'] >= -74.25) & (filtered_df['pickup_longitude'] <= -73.70) &
    (filtered_df['pickup_latitude'] >= 40.50) & (filtered_df['pickup_latitude'] <= 40.90) &
    (filtered_df['dropoff_longitude'] >= -74.25) & (filtered_df['dropoff_longitude'] <= -73.70) &
    (filtered_df['dropoff_latitude'] >= 40.50) & (filtered_df['dropoff_latitude'] <= 40.90)
]

# 重新计算经纬度的最大最小值
min_longitude = min(nyc_filtered_df['pickup_longitude'].min(), nyc_filtered_df['dropoff_longitude'].min())
max_longitude = max(nyc_filtered_df['pickup_longitude'].max(), nyc_filtered_df['dropoff_longitude'].max())
min_latitude = min(nyc_filtered_df['pickup_latitude'].min(), nyc_filtered_df['dropoff_latitude'].min())
max_latitude = max(nyc_filtered_df['pickup_latitude'].max(), nyc_filtered_df['dropoff_latitude'].max())

# 打印结果
print("Corrected Global Minimum Longitude:", min_longitude)
print("Corrected Global Maximum Longitude:", max_longitude)
print("Corrected Global Minimum Latitude:", min_latitude)
print("Corrected Global Maximum Latitude:", max_latitude)

Corrected Global Minimum Longitude: -74.25
Corrected Global Maximum Longitude: -73.70000457763672
Corrected Global Minimum Latitude: 40.50067138671875
Corrected Global Maximum Latitude: 40.89999771118164


In [6]:
nyc_filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33879003 entries, 0 to 33916983
Data columns (total 7 columns):
 #   Column                 Dtype  
---  ------                 -----  
 0   tpep_pickup_datetime   object 
 1   tpep_dropoff_datetime  object 
 2   passenger_count        int64  
 3   pickup_longitude       float64
 4   pickup_latitude        float64
 5   dropoff_longitude      float64
 6   dropoff_latitude       float64
dtypes: float64(4), int64(1), object(2)
memory usage: 2.0+ GB


In [ ]:
import pandas as pd
import numpy as np
import folium
from folium.plugins import HeatMap

# 创建基本地图
# 选择一个中心点，这里我们假设纽约市的中心点
map_center = [40.7128, -74.0060]  # 纽约市的大致中心经纬度
map = folium.Map(location=map_center, zoom_start=12)  # 调整地图的初始位置和缩放级别

# 添加热力图层
sampled_data = nyc_filtered_df.sample(n=30000, random_state=42)
heatmap_data = sampled_data[['pickup_latitude', 'pickup_longitude']].values.tolist()  # 将数据转换为列表
HeatMap(heatmap_data).add_to(map)
# sampled_data
# 保存地图
map.save('NYC_Taxi_Pickup_Heatmap.html')

print("Heatmap has been created and saved as 'NYC_Taxi_Pickup_Heatmap.html'")

In [7]:
# 筛选曼哈顿区的数据
manhattan_df = filtered_df[
    (filtered_df['pickup_longitude'] >= -74.0176) & (filtered_df['pickup_longitude'] <= -73.9067) &
    (filtered_df['pickup_latitude'] >= 40.6829) & (filtered_df['pickup_latitude'] <= 40.8820) &
    (filtered_df['dropoff_longitude'] >= -74.0176) & (filtered_df['dropoff_longitude'] <= -73.9067) &
    (filtered_df['dropoff_latitude'] >= 40.6829) & (filtered_df['dropoff_latitude'] <= 40.8820)
]

# 打印过滤后的数据信息以确认操作
print(manhattan_df.info())

# 重新计算经纬度的最大最小值
min_longitude = min(manhattan_df['pickup_longitude'].min(), manhattan_df['dropoff_longitude'].min())
max_longitude = max(manhattan_df['pickup_longitude'].max(), manhattan_df['dropoff_longitude'].max())
min_latitude = min(manhattan_df['pickup_latitude'].min(), manhattan_df['dropoff_latitude'].min())
max_latitude = max(manhattan_df['pickup_latitude'].max(), manhattan_df['dropoff_latitude'].max())

# 打印结果
print("Manhattan Minimum Longitude:", min_longitude)
print("Manhattan Maximum Longitude:", max_longitude)
print("Manhattan Minimum Latitude:", min_latitude)
print("Manhattan Maximum Latitude:", max_latitude)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30563697 entries, 0 to 33916982
Data columns (total 7 columns):
 #   Column                 Dtype  
---  ------                 -----  
 0   tpep_pickup_datetime   object 
 1   tpep_dropoff_datetime  object 
 2   passenger_count        int64  
 3   pickup_longitude       float64
 4   pickup_latitude        float64
 5   dropoff_longitude      float64
 6   dropoff_latitude       float64
dtypes: float64(4), int64(1), object(2)
memory usage: 1.8+ GB
None
Manhattan Minimum Longitude: -74.01759338378906
Manhattan Maximum Longitude: -73.90670013427734
Manhattan Minimum Latitude: 40.68290328979492
Manhattan Maximum Latitude: 40.881999969482415


In [9]:
import pandas as pd
import numpy as np
import folium
from folium.plugins import HeatMap

# 创建基本地图
# 选择一个中心点，这里我们假设纽约市的中心点
map_center = [40.7128, -74.0060]  # 纽约市的大致中心经纬度
map = folium.Map(location=map_center, zoom_start=12)  # 调整地图的初始位置和缩放级别

# 添加热力图层
sampled_data = manhattan_df.sample(n=30000, random_state=42)
heatmap_data = sampled_data[['pickup_latitude', 'pickup_longitude']].values.tolist()  # 将数据转换为列表
HeatMap(heatmap_data).add_to(map)
# sampled_data
# 保存地图
map.save('NYC_Taxi_Pickup_Heatmap.html')

print("Heatmap has been created and saved as 'NYC_Taxi_Pickup_Heatmap.html'")


Heatmap has been created and saved as 'NYC_Taxi_Pickup_Heatmap.html'


In [8]:
# 定义网格尺寸
n_rows = 30
n_columns = 15
lon_width = (74.0176 - 73.9067) / n_columns
lat_height = (40.8820 - 40.6829) / n_rows

# 计算网格编号
def calculate_grid_id(lon, lat):
    lon_idx = int((lon + 74.0176) / lon_width)
    lat_idx = int((40.8820 - lat) / lat_height)
    return lon_idx + lat_idx * n_columns

# 为每个行程添加网格编号
manhattan_df['pickup_grid_id'] = manhattan_df.apply(lambda x: calculate_grid_id(x['pickup_longitude'], x['pickup_latitude']), axis=1)
manhattan_df['dropoff_grid_id'] = manhattan_df.apply(lambda x: calculate_grid_id(x['dropoff_longitude'], x['dropoff_latitude']), axis=1)

# 打印更新后的DataFrame信息
print(manhattan_df[['pickup_grid_id', 'dropoff_grid_id']].head())

AnonymousUser\AppData\Local\Temp\ipykernel_2664\233278494.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  manhattan_df['pickup_grid_id'] = manhattan_df.apply(lambda x: calculate_grid_id(x['pickup_longitude'], x['pickup_latitude']), axis=1)
AnonymousUser\AppData\Local\Temp\ipykernel_2664\233278494.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  manhattan_df['dropoff_grid_id'] = manhattan_df.apply(lambda x: calculate_grid_id(x['dropoff_longitude'], x['dropoff_latitude']), axis=1)


   pickup_grid_id  dropoff_grid_id
0             333              334
1             334              369
4             232              275
5             305              269
6             363              201


In [9]:
# 按pickup_grid_id分组并计算每组的数据数
grouped_pickup_counts = manhattan_df.groupby('pickup_grid_id').size()

# 将结果转换为DataFrame并重置索引，方便查看
grouped_pickup_counts_df = grouped_pickup_counts.reset_index(name='count')

# 打印结果
print(grouped_pickup_counts_df)

     pickup_grid_id  count
0                 1      3
1                 2      5
2                 3      6
3                 4      1
4                 5      5
..              ...    ...
429             445    495
430             446    506
431             447    257
432             448    474
433             449    274

[434 rows x 2 columns]


In [10]:
print(grouped_pickup_counts_df)

     pickup_grid_id  count
0                 1      3
1                 2      5
2                 3      6
3                 4      1
4                 5      5
..              ...    ...
429             445    495
430             446    506
431             447    257
432             448    474
433             449    274

[434 rows x 2 columns]


In [11]:
# 按照计数排序
sorted_grouped_pickup_counts_df = grouped_pickup_counts_df.sort_values(by='count', ascending=False)

# 打印排序后的DataFrame以确认
print(sorted_grouped_pickup_counts_df)

# 输出到TXT文件
sorted_grouped_pickup_counts_df.to_csv('sorted_pickup_counts.txt', index=False, sep='\t')

     pickup_grid_id    count
272             288  1199944
274             290  1090846
260             276   984514
258             274   883917
243             259   853522
..              ...      ...
98              112        1
139             155        1
78               90        1
71               83        1
3                 4        1

[434 rows x 2 columns]


In [12]:
# 筛选出行程数大于或等于1000的网格编号
valid_pickup_grid_ids = grouped_pickup_counts_df[grouped_pickup_counts_df['count'] >= 1000]['pickup_grid_id']

# 使用这些网格编号过滤原始数据集
filtered_manhattan_df = manhattan_df[manhattan_df['pickup_grid_id'].isin(valid_pickup_grid_ids)]
filtered_manhattan_df = filtered_manhattan_df[filtered_manhattan_df['dropoff_grid_id'].isin(valid_pickup_grid_ids)]

# 打印过滤后的DataFrame以确认
print(filtered_manhattan_df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30245175 entries, 0 to 33916982
Data columns (total 9 columns):
 #   Column                 Dtype  
---  ------                 -----  
 0   tpep_pickup_datetime   object 
 1   tpep_dropoff_datetime  object 
 2   passenger_count        int64  
 3   pickup_longitude       float64
 4   pickup_latitude        float64
 5   dropoff_longitude      float64
 6   dropoff_latitude       float64
 7   pickup_grid_id         int64  
 8   dropoff_grid_id        int64  
dtypes: float64(4), int64(3), object(2)
memory usage: 2.3+ GB
None


In [13]:
# 创建新的网格编号映射
grid_id_mapping = {old_id: new_id for new_id, old_id in enumerate(valid_pickup_grid_ids)}

# 为数据集应用新的网格编号
filtered_manhattan_df['new_pickup_grid_id'] = filtered_manhattan_df['pickup_grid_id'].map(grid_id_mapping)
filtered_manhattan_df['new_dropoff_grid_id'] = filtered_manhattan_df['dropoff_grid_id'].map(grid_id_mapping)

In [14]:
# 计算每个网格中心的坐标
grid_centers = []
for grid_id in valid_pickup_grid_ids:
    lat_idx = grid_id // n_columns
    lon_idx = grid_id % n_columns
    center_lon = -74.0176 + lon_idx * lon_width + lon_width / 2
    center_lat = 40.8820 - lat_idx * lat_height - lat_height / 2
    grid_centers.append((center_lon, center_lat))

In [15]:
# 将网格中心坐标转换为DataFrame
grid_centers_df = pd.DataFrame(grid_centers, columns=['Longitude', 'Latitude'])
grid_centers_df['New_Grid_ID'] = grid_centers_df.index  # 添加新网格编号

# 打印网格中心坐标表
print(grid_centers_df)

# 保存网格中心坐标表到CSV
grid_centers_df.to_csv('grid_centers.csv', index=False)

     Longitude   Latitude  New_Grid_ID
0   -73.925183  40.865408            0
1   -73.932577  40.858772            1
2   -73.939970  40.852135            2
3   -73.932577  40.852135            3
4   -73.939970  40.845498            4
..         ...        ...          ...
201 -73.984330  40.686218          201
202 -73.976937  40.686218          202
203 -73.969543  40.686218          203
204 -73.962150  40.686218          204
205 -73.954757  40.686218          205

[206 rows x 3 columns]


In [ ]:
import matplotlib.pyplot as plt

# 假设grid_centers_df是包含所有网格中心坐标的DataFrame
# 如果已经保存为CSV，可以使用以下代码重新加载
# grid_centers_df = pd.read_csv('grid_centers.csv')

# 绘制网格中心点
plt.figure(figsize=(3, 8))
plt.scatter(grid_centers_df['Longitude'], grid_centers_df['Latitude'], marker='o', color='b', label='Grid Centers')

# 设置图表标题和标签
plt.title('Manhattan Grid Centers')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.grid(True)  # 显示网格线

# 添加图例
plt.legend()

# 显示图形
plt.show()

In [17]:
# 删除指定列
columns_to_drop = ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude', 'pickup_grid_id', 'dropoff_grid_id']
filtered_manhattan_df.drop(columns=columns_to_drop, inplace=True)

# 输出到CSV文件
filtered_manhattan_df.to_csv('filtered_manhattan_df.csv', index=False)

## Filtered Manhattan DF

In [20]:
import pandas as pd

filtered_manhattan_df = pd.read_csv('filtered_manhattan_df.csv')

In [21]:
filtered_manhattan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30245175 entries, 0 to 30245174
Data columns (total 5 columns):
 #   Column                 Dtype 
---  ------                 ----- 
 0   tpep_pickup_datetime   object
 1   tpep_dropoff_datetime  object
 2   passenger_count        int64 
 3   new_pickup_grid_id     int64 
 4   new_dropoff_grid_id    int64 
dtypes: int64(3), object(2)
memory usage: 1.1+ GB


In [22]:
# 从 filtered_manhattan_df 中选择指定的列，创建 pickup_df
pickup_df = filtered_manhattan_df.loc[:, ['tpep_pickup_datetime', 'passenger_count', 'new_pickup_grid_id']]

# 从 filtered_manhattan_df 中选择指定的列，创建 dropoff_df
dropoff_df = filtered_manhattan_df.loc[:, ['tpep_dropoff_datetime', 'passenger_count', 'new_dropoff_grid_id']]

In [23]:
pickup_df.to_csv('pickup_df.csv', index=False)
dropoff_df.to_csv('dropoff_df.csv', index=False)

## Pickup DF

In [2]:
import pandas as pd

# 设置开始和结束日期
start_date = '2016-01-01 00:00:00'
end_date = '2016-03-31 23:59:59'

# 生成时间序列，间隔为30分钟
time_slices = pd.date_range(start=start_date, end=end_date, freq='30T')

time_slices

DatetimeIndex(['2016-01-01 00:00:00', '2016-01-01 00:30:00',
               '2016-01-01 01:00:00', '2016-01-01 01:30:00',
               '2016-01-01 02:00:00', '2016-01-01 02:30:00',
               '2016-01-01 03:00:00', '2016-01-01 03:30:00',
               '2016-01-01 04:00:00', '2016-01-01 04:30:00',
               ...
               '2016-03-31 19:00:00', '2016-03-31 19:30:00',
               '2016-03-31 20:00:00', '2016-03-31 20:30:00',
               '2016-03-31 21:00:00', '2016-03-31 21:30:00',
               '2016-03-31 22:00:00', '2016-03-31 22:30:00',
               '2016-03-31 23:00:00', '2016-03-31 23:30:00'],
              dtype='datetime64[ns]', length=4368, freq='30T')

In [3]:
pickup_df = pd.read_csv('pickup_df.csv')
pickup_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30245175 entries, 0 to 30245174
Data columns (total 3 columns):
 #   Column                Dtype 
---  ------                ----- 
 0   tpep_pickup_datetime  object
 1   passenger_count       int64 
 2   new_pickup_grid_id    int64 
dtypes: int64(2), object(1)
memory usage: 692.3+ MB


In [4]:
# 将tpep_pickup_datetime列转换为Datetime类型
pickup_df['tpep_pickup_datetime'] = pd.to_datetime(pickup_df['tpep_pickup_datetime'])

In [5]:
# 创建一个新列表示时间片段（每30分钟）
pickup_df['time_slice'] = pickup_df['tpep_pickup_datetime'].dt.floor('30min')

# 按照时间片段和网格编号进行分组，并统计每个分组中的记录数和乘客总数
grouped = pickup_df.groupby(['time_slice', 'new_pickup_grid_id']).agg({'passenger_count': 'sum', 'new_pickup_grid_id': 'count'})

In [6]:
grouped.head(10)

passenger_count  new_pickup_grid_id
time_slice new_pickup_grid_id                                     
2016-01-01 2                                 7                   5
           3                                 5                   5
           4                                 2                   2
           6                                14                   7
           7                                 1                   1
           8                                 1                   1
           9                                 9                   5
           10                               24                  10
           11                               14                   8
           12                                5                   4

In [7]:
grouped.tail(10)

passenger_count  new_pickup_grid_id
time_slice          new_pickup_grid_id                                     
2016-03-31 23:30:00 191                              14                   7
                    192                               2                   2
                    193                               1                   1
                    195                               1                   1
                    199                               1                   1
                    201                               1                   1
                    202                               7                   4
                    203                               3                   2
                    204                               1                   1
                    205                               7                   2

In [70]:
for i, time_slice in enumerate(time_slices):
    print(i, time_slice)

0 2016-01-01 00:00:00
1 2016-01-01 00:30:00
2 2016-01-01 01:00:00
3 2016-01-01 01:30:00
4 2016-01-01 02:00:00
5 2016-01-01 02:30:00
6 2016-01-01 03:00:00
7 2016-01-01 03:30:00
8 2016-01-01 04:00:00
9 2016-01-01 04:30:00
10 2016-01-01 05:00:00
11 2016-01-01 05:30:00
12 2016-01-01 06:00:00
13 2016-01-01 06:30:00
14 2016-01-01 07:00:00
15 2016-01-01 07:30:00
16 2016-01-01 08:00:00
17 2016-01-01 08:30:00
18 2016-01-01 09:00:00
19 2016-01-01 09:30:00
20 2016-01-01 10:00:00
21 2016-01-01 10:30:00
22 2016-01-01 11:00:00
23 2016-01-01 11:30:00
24 2016-01-01 12:00:00
25 2016-01-01 12:30:00
26 2016-01-01 13:00:00
27 2016-01-01 13:30:00
28 2016-01-01 14:00:00
29 2016-01-01 14:30:00
30 2016-01-01 15:00:00
31 2016-01-01 15:30:00
32 2016-01-01 16:00:00
33 2016-01-01 16:30:00
34 2016-01-01 17:00:00
35 2016-01-01 17:30:00
36 2016-01-01 18:00:00
37 2016-01-01 18:30:00
38 2016-01-01 19:00:00
39 2016-01-01 19:30:00
40 2016-01-01 20:00:00
41 2016-01-01 20:30:00
42 2016-01-01 21:00:00
43 2016-01-01 21:30:0

In [71]:
import numpy as np

# 将结果重塑为所需的形状
# time_slices = sorted(pickup_df['time_slice'].unique())  # 获取所有时间片段
grid_ids = sorted(pickup_df['new_pickup_grid_id'].unique())  # 获取所有网格编号
pick_out = np.zeros((len(time_slices), len(grid_ids), 2), dtype=int)  # 创建空的结果数组

# 填充结果数组
for i, time_slice in enumerate(time_slices):
    for j, grid_id in enumerate(grid_ids):
        try:
            count = grouped.loc[(time_slice, grid_id), 'new_pickup_grid_id']
            passengers = grouped.loc[(time_slice, grid_id), 'passenger_count']
        except KeyError:
            count = 0
            passengers = 0
        pick_out[i, j, 0] = count
        pick_out[i, j, 1] = passengers

# 输出结果
print(pick_out)

[[[ 0  0]
  [ 0  0]
  [ 5  7]
  ...
  [ 1  1]
  [ 0  0]
  [ 1  1]]

 [[11 24]
  [ 6  9]
  [ 9 16]
  ...
  [ 7 12]
  [ 3 12]
  [ 6  9]]

 [[ 7  8]
  [ 4  6]
  [ 7 19]
  ...
  [ 9 17]
  [ 4  5]
  [16 26]]

 ...

 [[ 3  4]
  [ 0  0]
  [ 3  5]
  ...
  [ 1  2]
  [ 1  1]
  [ 1  1]]

 [[ 2  3]
  [ 0  0]
  [ 0  0]
  ...
  [ 1  1]
  [ 0  0]
  [ 0  0]]

 [[ 2  4]
  [ 0  0]
  [ 2  2]
  ...
  [ 2  3]
  [ 1  1]
  [ 2  7]]]


In [44]:
pick_out.shape

(13092, 206, 2)

## Dropout DF

In [72]:
dropoff_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30245175 entries, 0 to 30245174
Data columns (total 4 columns):
 #   Column                 Dtype         
---  ------                 -----         
 0   tpep_dropoff_datetime  datetime64[ns]
 1   passenger_count        int64         
 2   new_dropoff_grid_id    int64         
 3   time_slice             datetime64[ns]
dtypes: datetime64[ns](2), int64(2)
memory usage: 923.0 MB


In [73]:
# 将tpep_dropoff_datetime列转换为Datetime类型
dropoff_df['tpep_dropoff_datetime'] = pd.to_datetime(dropoff_df['tpep_dropoff_datetime'])

In [75]:
# 创建一个新列表示时间片段（每10分钟）
dropoff_df['time_slice'] = dropoff_df['tpep_dropoff_datetime'].dt.floor('30min')

# 按照时间片段和网格编号进行分组，并统计每个分组中的记录数和乘客总数
dropoff_df_grouped = dropoff_df.groupby(['time_slice', 'new_dropoff_grid_id']).agg({'passenger_count': 'sum', 'new_dropoff_grid_id': 'count'})

In [76]:
dropoff_df_grouped.head

<bound method NDFrame.head of                                          passenger_count  new_dropoff_grid_id
time_slice          new_dropoff_grid_id                                      
2016-01-01 00:00:00 0                                  8                    6
                    1                                  3                    1
                    2                                  3                    2
                    3                                 12                   11
                    4                                  5                    5
...                                                  ...                  ...
2016-03-31 23:30:00 201                               19                   12
                    202                               32                   19
                    203                               19                   10
                    204                               23                   17
                    205           

In [78]:
import numpy as np

# 将结果重塑为所需的形状
# time_slices = sorted(dropoff_df['time_slice'].unique())  # 获取所有时间片段
grid_ids = sorted(dropoff_df['new_dropoff_grid_id'].unique())  # 获取所有网格编号
drop_in = np.zeros((len(time_slices), len(grid_ids), 2), dtype=int)  # 创建空的结果数组

# 填充结果数组
for i, time_slice in enumerate(time_slices):
    for j, grid_id in enumerate(grid_ids):
        try:
            count = dropoff_df_grouped.loc[(time_slice, grid_id), 'new_dropoff_grid_id']
            passengers = dropoff_df_grouped.loc[(time_slice, grid_id), 'passenger_count']
        except KeyError:
            count = 0
            passengers = 0
        drop_in[i, j, 0] = count
        drop_in[i, j, 1] = passengers

# 输出结果
print(drop_in)

[[[ 6  8]
  [ 1  3]
  [ 2  3]
  ...
  [ 1  1]
  [ 2  2]
  [ 2  2]]

 [[16 31]
  [12 21]
  [16 31]
  ...
  [11 14]
  [ 5 10]
  [ 7 15]]

 [[17 21]
  [16 26]
  [20 37]
  ...
  [15 29]
  [ 2  4]
  [15 18]]

 ...

 [[14 27]
  [13 21]
  [18 31]
  ...
  [19 32]
  [13 14]
  [12 16]]

 [[15 19]
  [14 18]
  [18 28]
  ...
  [17 26]
  [16 20]
  [13 16]]

 [[17 39]
  [ 9 18]
  [21 35]
  ...
  [10 19]
  [17 23]
  [21 33]]]


In [79]:
drop_in.shape

(4368, 206, 2)

## Merge Pick & Drop

In [1]:
# 使用 concatenate 函数拼接数组
pick_out_drop_in = np.concatenate((pick_out, drop_in), axis=-1)

# 输出结果数组的形状
print(pick_out_drop_in.shape)

NameError: name 'np' is not defined

## PickUp CrowdOut DropOff CrowdIn

In [97]:
# 分离每个数据维度
pick_up = pick_out_drop_in[:, :, 0]
crowd_out = pick_out_drop_in[:, :, 1]
drop_off = pick_out_drop_in[:, :, 2]
crowd_in = pick_out_drop_in[:, :, 3]

# 展示每个数组的形状
pick_up.shape, crowd_out.shape, drop_off.shape, crowd_in.shape

((4368, 206), (4368, 206), (4368, 206), (4368, 206))

In [98]:
np.save('pickup.npy', pick_up.T)
np.save('crowdout.npy', crowd_out.T)
np.save('dropoff.npy', drop_off.T)
np.save('crowdin.npy', crowd_in.T)

In [99]:
import pandas as pd

grid_centers = pd.read_csv('grid_centers.csv')

In [102]:
# 保存前两列数据为numpy数组
grid_centers_np = grid_centers.iloc[:, :2].values

In [103]:
grid_centers_np

array([[-73.92518333,  40.86540833],
       [-73.93257667,  40.85877167],
       [-73.93997   ,  40.852135  ],
       [-73.93257667,  40.852135  ],
       [-73.93997   ,  40.84549833],
       [-73.94736333,  40.83886167],
       [-73.93997   ,  40.83886167],
       [-73.91779   ,  40.83886167],
       [-73.94736333,  40.832225  ],
       [-73.93997   ,  40.832225  ],
       [-73.95475667,  40.82558833],
       [-73.94736333,  40.82558833],
       [-73.93997   ,  40.82558833],
       [-73.92518333,  40.82558833],
       [-73.96215   ,  40.81895167],
       [-73.95475667,  40.81895167],
       [-73.94736333,  40.81895167],
       [-73.93997   ,  40.81895167],
       [-73.92518333,  40.81895167],
       [-73.96215   ,  40.812315  ],
       [-73.95475667,  40.812315  ],
       [-73.94736333,  40.812315  ],
       [-73.93997   ,  40.812315  ],
       [-73.93257667,  40.812315  ],
       [-73.92518333,  40.812315  ],
       [-73.96954333,  40.80567833],
       [-73.96215   ,  40.80567833],
 

In [104]:
np.save('coordinates.npy', grid_centers_np)